name: Generate R Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - name: Install Dependencies
      run: Rscript -e 'install.packages(c("devtools", "testthat", "covr", "dplyr", "ggplot2"))'
    - name: Generate Package
      run: Rscript -e 'devtools::build()'
    - name: Check Package
      run: Rscript -e 'devtools::check()'
    - name: Test Package
      run: Rscript -e 'testthat::test_dir("tests/")'
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        flags: unittests